### ISSUE TITLE
Not working in N. California region

### ISSUE THREAD

**Issue by jmineroff** [m-chandler/factorio-spot-pricing#14]
I just tried to run this through the link and got the following error:
`'S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html'`

I get the same error even if I download the YAML and upload it directly.

If I load the YAML manually and try to view it in the designer, I get:
`Cannot convert the template because of an error:: JSON Parse error: Unexpected identifier "AWSTemplateFormatVersion"`

**Comment by m-chandler** [comment]
Hey @jmineroff, I've never used the CloudFormation Designer, it doesn't seem to support everything that CloudFormation does unfortunately.

In the short term, can you please try and just save the YML file to your computer, and then via CloudFormation click Create Stack > Template is Ready > Upload a Template File. This works fine for me.

I might look into the CloudFormation designer issue but... probably not.

I feel like I've fixed this regional issue before. Either AWS keep changing things or I never fixed it in the first place (works fine on my AWS account in N. California, I'll try my secondary account).

**Comment by m-chandler** [comment]
@jmineroff , should be fixed now (not the CloudFormation designer, but the link itself).

I confirmed the issue with my secondary AWS account and fixed the issue / verified the fix.

Closing this issue, please re-open if you still encounter the issue or need further assistance.

Cheers.
