### ISSUE TITLE
Error InterruptibleStdioStream.cpp:61

### ISSUE THREAD

**Issue by Zemnmez** [m-chandler/factorio-spot-pricing#22]
As far as I know, I've followed the instructions correctly. I restarted the server via ECS and got    3.559 Error InterruptibleStdioStream.cpp:61: Got EOF on stdin; closing

**Comment by Zemnmez** [comment]
I don't know if this is expected, but it seems to have mounted a new ECS volume each time

**Comment by Zemnmez** [comment]
restarted a few more times and got the same error. At a loss as to what it might mean. Not able to connect via the game

**Comment by m-chandler** [comment]
Are you trying to use an existing save?

Does it work if you don't try to load an existing save and just start a new game? Without any mods.
Could you check the logs for any other warnings further up? (See: https://github.com/factoriotools/factorio-docker/issues/427)

RE: New ECS volume I'm not sure what you mean. 
EBS volume? The EBS volume on the EC2 instance on which the ECS task runs is not important, it's just the Linux OS + Docker agent. The EBS volume will get terminated when the EC2 instance does. No data is stored on it. All persistent data is stored on EFS, which will not get replaced unless you delete / redeploy the entire CloudFormation stack.

**Comment by Zemnmez** [comment]
Yes I'm using an existing save. Sorry, I probably meant EBS volume. I've just built a new server and I'll see if I can connect

**Comment by Zemnmez** [comment]
Server doesn't initially work, I think this is because it's public by default and I didn't provide a token. I will now configure the server

**Comment by Zemnmez** [comment]
OK! So I was able to find the issue! The EOF in the error log is not a server failure. The issue is that the DNS record had not propagated yet.

Sorry!!

**Comment by m-chandler** [comment]
Cool, glad you got it sorted anyway!

**Comment by Zemnmez** [comment]
thanks so much! crazy you responded so fast
