### ISSUE TITLE
Lambda EOL for Python 3.7

### ISSUE THREAD

**Issue by jmineroff** [m-chandler/factorio-spot-pricing#23]
AWS is ending support for Python 3.7 on November 27th. I don't think there is any significant impact of this, but is there any reason not to update the Python version here to 3.11?

https://github.com/m-chandler/factorio-spot-pricing/blob/689e3c87a851a331c4b084cc211d5d90b29ce6bd/cf.yml#L437C7-L437C25

**Comment by robinld** [comment]
I don't see anything in that script that should care about 3.7->3.11

**Comment by m-chandler** [comment]
Happy to take a PR! Otherwise I’ll get to it at some point.

**Comment by robinld** [comment]
@m-chandler I made a PR https://github.com/m-chandler/factorio-spot-pricing/pull/24

**Comment by m-chandler** [comment]
Thanks all; have merged #24

**Comment by mnemonicly** [comment]
Hello--It looks like the linked file in the readme still uses python3.7.  I ran into the same issue with a new setup today.  Was able to edit the file and move on.

**Comment by m-chandler** [comment]
Thanks @dmeltzer.
I forget that I need to manually upload the file to my bucket when changes are made. Have done this now.
