### ISSUE TITLE
CREATE_FAILED

### ISSUE THREAD

**Issue by patate1684** [m-chandler/factorio-spot-pricing#30]
I folowed the instruction and make sure to chose an instance type that is availible in my region but got this error

> Resource handler returned message: "The Launch Configuration creation operation is not available in your account. Use launch templates to create configuration templates for your Auto Scaling groups. (Service: AutoScaling, Status Code: 400, Request ID: acf9bd9e-f9e3-4687-b04b-f9166487c69c)" (RequestToken: 3ff8283a-12ab-d86e-6de8-8f665efca00b, HandlerErrorCode: GeneralServiceException)

I tried again multiple time with different instance type with no success

![image](https://github.com/user-attachments/assets/ca218c69-d004-450d-80c2-292d863c430e)

**Comment by m-chandler** [comment]
Looks like Launch Configurations have been deprecated on new accounts
created after 01/10/24.

https://github.com/SummitRoute/aws_breaking_changes/issues/95

Sorry, I will have to review the template when I get a chance.

**Comment by m-chandler** [comment]
@patate1684 fixed in latest commit, should be working now.
