### ISSUE TITLE
 VPC reuse

### ISSUE THREAD

**Issue by robertmassaioli** [m-chandler/factorio-spot-pricing#33]
According to https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html you can only have 5VPC's per region.I just wanted to set up 5 different servers for a work event and ran into that limitation. How would you recommend I get around this? Is there a way to reuse the same VPC across different factorio servers?

![Screenshot 2024-10-09 at 3 19 30 pm](https://github.com/user-attachments/assets/c5789a64-9ae0-4eee-8383-723f6e6cf8f9)

**Comment by m-chandler** [comment]
The template would a few tweaks to re-use an existing VPC.

The easiest/fastest way would be just to create another AWS account and deploy your 5th and further servers there. Alternatively you could request a limit increase from AWS, however this might be as quick as you'd like.

**Comment by robertmassaioli** [comment]
Hey @m-chandler , so, instead of trying to reuse a VPC across two different cloudformation stacks, I've just auto-generated multiple ASGs etc. inside of one cloud formation stack and parameterised everything.

Take a look here on this branch: https://github.com/robertmassaioli/factorio-spot-pricing/tree/multi-instance/templates

I can confirm that the 20-servers one seems to work just fine and I've given them all an associated bash script to work with.

Let me know what you think...if you want, we could even merge this in and make a 1, 2 or 3-server version that is the default for people. That way it's easy for them to spin up multiple instances later.

**Comment by m-chandler** [comment]
Resolved by [1fa6060f703b8ee412b948b3cf56014273985c53](https://github.com/m-chandler/factorio-spot-pricing/commit/1fa6060f703b8ee412b948b3cf56014273985c53)
