### ISSUE TITLE
Upload Save Scripted

### ISSUE THREAD

**Issue by robertmassaioli** [m-chandler/factorio-spot-pricing#34]
Hi,

Did you want to steal my upload-save.bash script: https://github.com/robertmassaioli/factorio-spot-pricing/blob/multi-instance/upload-save.bash

It makes that 8 step process take all of 2 seconds.

Note: That you should wait for ECS and EC2 to report the instance is healthy before running the script and killing the docker container.

**Comment by m-chandler** [comment]
Resovled by https://github.com/m-chandler/factorio-spot-pricing/commit/9ad64993477c849da2e487b0c8c3034ff9eadb88
