### ISSUE TITLE
No Container Instances were found in your cluster

### ISSUE THREAD

**Issue by vatertime** [m-chandler/factorio-spot-pricing#4]
EcsService setup hangs due to error. May be related to [insufficient roles assigned to task](https://stackoverflow.com/questions/36523282/aws-ecs-error-when-running-task-no-container-instances-were-found-in-your-clust/36533601).

"service factorio was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster. For more information, see the Troubleshooting section. "

![no-container-instance](https://user-images.githubusercontent.com/1236789/61958748-8b0f6b00-af87-11e9-9342-9b90850a7d57.png)

**Comment by apeabody** [comment]
@vatertime A screenshot of your ECS->Clusters->factorio-> ECS Instances might help.

**Comment by vatertime** [comment]
No instances exist, because none could be created.

![instances-tab](https://user-images.githubusercontent.com/1236789/62059192-5e0dc300-b1e8-11e9-81ab-798956c56aea.png)

**Comment by vatertime** [comment]
m3.medium instances are no longer available. Update to t3.medium and deployment works correctly.
https://aws.amazon.com/ec2/previous-generation/

**Comment by apeabody** [comment]
Ahh, yes - instance availability varies by region.  For example: spot m3.mediums are available in Virginia & Oregon, but not Ohio.  You can see per region along with current spot pricing here: https://aws.amazon.com/ec2/spot/pricing/
