### ISSUE TITLE
CloudFormation Template S3 Redirect

### ISSUE THREAD

**Issue by syntaxfern** [m-chandler/factorio-spot-pricing#7]
Getting this error on using the `Launch Stack` button.

Easy enough to work around. Just a heads up.

```xml
<Error>
<Code>PermanentRedirect</Code>
<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>
<Endpoint>factorio-spot-pricing.s3.amazonaws.com</Endpoint>
<Bucket>factorio-spot-pricing</Bucket>
<RequestId>B9394F269BE4D795</RequestId>
<HostId>
985qocfJ7DXoqHsPGvZpZ+ONlheRqQ5evU33LPSoSsmfusdzXhuk8YzRcpO7Td8JeHExtw0ob2I=
</HostId>
</Error>
```

**Comment by Jim-Bar** [comment]
I have the same error message when using the `Next` button on the first step. Trying to replace the URL did not help in any way.

Can you describe in more depth how to workaround this? I'm not familiar with AWS.

**Comment by syntaxfern** [comment]
You can choose a yml file to upload instead of the S3 url. In this case, the `cf.yml` in this repo.

**Comment by m-chandler** [comment]
Thanks, will look at this shortly. Feel free to submit PR.

**Comment by syntaxfern** [comment]
Unfortunately, this looks to be related to a file you're hosting on S3. Possibly related to Availability Zones.

**Comment by m-chandler** [comment]
Looked like bucket permissions. really strange. 
Worked in the same region of the bucket in another account.
Worked in the same region of the bucket and different regions in the bucket owner account.
Made file public, tested in another account... looks to work.

**Comment by m-chandler** [comment]
Thanks all.
