### ISSUE TITLE
Add ability to create multiple deployments in the same AWS account

### ISSUE THREAD

**Issue by audiodude** [m-chandler/factorio-spot-pricing#9]
When I try to create a second deployment of the CloudFormation, it seems to die with lots of errors about conflicting names. Perhaps the name of the service could be parameterized, or based off the deployment's name, so this doesn't happen?

The use case is to host two different games for different groups of friends.

**Comment by audiodude** [comment]
I figured out how to do this by just copying the yml file and replacing things that looked like `*Name: factorio-*` with `factorio2-*`

**Comment by m-chandler** [comment]
Fixed. https://github.com/m-chandler/factorio-spot-pricing/commit/b8f48b11cb25cb1f1ea77e23e804273894c7c2a2

**Comment by audiodude** [comment]
Awesome, thanks so much!
